#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"
ENV_FILE="${ROOT_DIR}/.env"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info() { echo -e "${CYAN}$*${NC}"; }
ok() { echo -e "${GREEN}$*${NC}"; }
warn() { echo -e "${YELLOW}$*${NC}"; }
err() { echo -e "${RED}$*${NC}"; }

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Command '$1' not found. Please install it first."
    exit 1
  fi
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    date +%s%N | sha256sum | cut -c1-32
  fi
}

is_port_in_use() {
  local port="$1"

  if command -v ss >/dev/null 2>&1; then
    ss -tlnH "sport = :${port}" 2>/dev/null | grep -q .
    return
  fi

  if command -v netstat >/dev/null 2>&1; then
    netstat -tln 2>/dev/null | grep -q ":${port} "
    return
  fi

  return 1
}

pick_free_port() {
  local port="$1"
  local max="$2"
  local candidate="$port"

  while [ "$candidate" -le "$max" ]; do
    if ! is_port_in_use "$candidate"; then
      echo "$candidate"
      return 0
    fi
    candidate=$((candidate + 1))
  done

  err "No free port found between ${port} and ${max}."
  exit 1
}

prompt_host_port() {
  local var_name="$1"
  local description="$2"
  local preferred="$3"
  local free
  local chosen
  local current

  free="$(pick_free_port "$preferred" $((preferred + 100)))"

  if [ "$free" != "$preferred" ]; then
    warn "Port ${preferred} is already in use on this host."
    ok "    Suggested free port: ${free}"
  fi

  prompt_value "$var_name" "$description" "$free" false false
  chosen="${!var_name}"

  while is_port_in_use "$chosen"; do
    warn "Port ${chosen} is already in use."
    chosen="$(pick_free_port "$((chosen + 1))" $((chosen + 100)))"
    ok "    Using port ${chosen} instead."
  done

  printf -v "$var_name" '%s' "$chosen"
}

prompt_value() {
  local key="$1"
  local description="$2"
  local default="${3:-}"
  local required="${4:-false}"
  local secret="${5:-false}"
  local input=""

  echo ""
  echo -e "${BOLD}>>> ${key}${NC}"
  echo "    ${description}"

  if [ "$secret" = "true" ]; then
    if [ -n "$default" ]; then
      read -rsp "    Value (Enter = default): " input
      echo ""
    else
      read -rsp "    Value: " input
      echo ""
    fi
  else
    if [ -n "$default" ]; then
      read -rp "    Value [${default}]: " input
    else
      read -rp "    Value: " input
    fi
  fi

  if [ -z "$input" ]; then
    input="$default"
  fi

  if [ "$required" = "true" ] && [ -z "$input" ]; then
    err "    '${key}' is required."
    prompt_value "$key" "$description" "$default" "$required" "$secret"
    return
  fi

  printf -v "$key" '%s' "$input"
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Telegram
BOT_TOKEN=${BOT_TOKEN}
WEBHOOK_URL=${WEBHOOK_URL}
WEBHOOK_PATH=${WEBHOOK_PATH}
WEBHOOK_SECRET=${WEBHOOK_SECRET}
PORT=${PORT}

# PostgreSQL
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
DATABASE_URL=${DATABASE_URL}

# Redis
REDIS_PORT=${REDIS_PORT}
REDIS_URL=${REDIS_URL}

# App
LOG_LEVEL=${LOG_LEVEL}
ADMIN_IDS=${ADMIN_IDS}

# Tron / Wallet
TRONGRID_API_KEY=${TRONGRID_API_KEY}
TRON_NETWORK=${TRON_NETWORK}
TRON_FULL_HOST=${TRON_FULL_HOST}
SWAPWALLET_API_KEY=${SWAPWALLET_API_KEY}

# Cron
DEPOSIT_MONITOR_CRON=${DEPOSIT_MONITOR_CRON}
WALLET_SWEEP_CRON=${WALLET_SWEEP_CRON}
OUTBOUND_USAGE_BILLING_CRON=${OUTBOUND_USAGE_BILLING_CRON}
PANEL_USAGE_BILLING_CRON=${PANEL_USAGE_BILLING_CRON}
OUTBOUND_VOLUME_ALERT_CRON=${OUTBOUND_VOLUME_ALERT_CRON}

# PasarGuard
PASARGUARD_TIMEOUT_MS=${PASARGUARD_TIMEOUT_MS}
PASARGUARD_MAX_RETRIES=${PASARGUARD_MAX_RETRIES}

# Tools
ADMINER_PORT=${ADMINER_PORT}
EOF
}

main() {
  clear || true
  echo -e "${BOLD}========================================${NC}"
  echo -e "${BOLD}   PanelOut Bot — Docker Setup${NC}"
  echo -e "${BOLD}========================================${NC}"
  echo ""
  info "This script collects environment variables, creates .env, and starts the stack with Docker."
  echo ""

  require_command docker

  if docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD=(docker compose)
  elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_CMD=(docker-compose)
  else
    err "Neither 'docker compose' nor 'docker-compose' was found."
    exit 1
  fi

  USE_DOCKER_INFRA="y"
  read -rp "Use PostgreSQL and Redis inside Docker? [Y/n]: " USE_DOCKER_INFRA
  USE_DOCKER_INFRA="${USE_DOCKER_INFRA:-y}"

  # --- Telegram ---
  prompt_value BOT_TOKEN "Telegram bot token from @BotFather" "" true true
  prompt_value WEBHOOK_URL "Public webhook base URL (without /webhook), e.g. https://bot.example.com" "" true false
  WEBHOOK_URL="${WEBHOOK_URL%/}"

  DEFAULT_WEBHOOK_SECRET="$(generate_secret)"
  prompt_value WEBHOOK_SECRET "Webhook secret (random string)" "$DEFAULT_WEBHOOK_SECRET" true true
  prompt_value WEBHOOK_PATH "Webhook path" "/webhook" false false
  prompt_host_port PORT "Application port (host)" 4444

  # --- Database ---
  if [[ "$USE_DOCKER_INFRA" =~ ^[Yy]$ ]]; then
    prompt_value POSTGRES_USER "PostgreSQL username" "panelout" true false
    prompt_value POSTGRES_PASSWORD "PostgreSQL password" "$(generate_secret)" true true
    prompt_value POSTGRES_DB "PostgreSQL database name" "panelout" true false
    prompt_host_port POSTGRES_PORT "PostgreSQL host port (external access)" 5432
    DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    ok "    DATABASE_URL set for Docker network: postgres:5432"
  else
    POSTGRES_USER=""
    POSTGRES_PASSWORD=""
    POSTGRES_DB=""
    POSTGRES_PORT="5432"
    prompt_value DATABASE_URL "Full DATABASE_URL (if the app runs in Docker and DB is on the host, use host.docker.internal instead of localhost)" "" true false
  fi

  # --- Redis ---
  if [[ "$USE_DOCKER_INFRA" =~ ^[Yy]$ ]]; then
    prompt_host_port REDIS_PORT "Redis host port (external access)" 6379
    REDIS_URL="redis://redis:6379"
    ok "    REDIS_URL set for Docker network: redis:6379"
  else
    REDIS_PORT="6379"
    prompt_value REDIS_URL "Redis URL (for a local Redis from Docker use redis://host.docker.internal:6379)" "" true false
  fi

  # --- App ---
  prompt_value LOG_LEVEL "Log level (debug/info/warn/error/fatal)" "info" false false
  prompt_value ADMIN_IDS "Admin Telegram user IDs (comma-separated)" "" false false

  # --- Tron ---
  prompt_value TRONGRID_API_KEY "TronGrid API key" "" true true
  prompt_value TRON_NETWORK "Tron network (mainnet or shasta)" "mainnet" true false
  prompt_value TRON_FULL_HOST "Tron API base URL (optional — set for shasta)" "" false false
  prompt_value SWAPWALLET_API_KEY "SwapWallet API key" "" true true

  # --- Cron ---
  prompt_value DEPOSIT_MONITOR_CRON "Deposit monitor cron" "*/30 * * * * *" false false
  prompt_value WALLET_SWEEP_CRON "Wallet sweep cron" "0 */10 * * * *" false false
  prompt_value OUTBOUND_USAGE_BILLING_CRON "Outbound usage billing cron" "*/20 * * * * *" false false
  prompt_value PANEL_USAGE_BILLING_CRON "Panel usage billing cron" "*/20 * * * * *" false false
  prompt_value OUTBOUND_VOLUME_ALERT_CRON "Outbound volume alert cron" "0 */5 * * * *" false false

  # --- PasarGuard ---
  prompt_value PASARGUARD_TIMEOUT_MS "PasarGuard request timeout (ms)" "30000" false false
  prompt_value PASARGUARD_MAX_RETRIES "PasarGuard max retries" "3" false false

  # --- Tools ---
  prompt_host_port ADMINER_PORT "Adminer port (tools profile only)" 8080

  echo ""
  warn "Writing .env file..."
  if [ -f "$ENV_FILE" ]; then
    BACKUP_FILE="${ENV_FILE}.bak.$(date +%s)"
    cp "$ENV_FILE" "$BACKUP_FILE"
    ok "Previous .env backed up to: ${BACKUP_FILE}"
  fi

  write_env_file
  ok ".env saved."

  echo ""
  info "Building Docker image..."
  "${COMPOSE_CMD[@]}" build

  echo ""
  info "Starting services..."
  if [[ "$USE_DOCKER_INFRA" =~ ^[Yy]$ ]]; then
    "${COMPOSE_CMD[@]}" --profile infra up -d postgres redis app
  else
    "${COMPOSE_CMD[@]}" up -d app
  fi

  echo ""
  info "Waiting for the application to become ready..."
  sleep 5
  "${COMPOSE_CMD[@]}" ps

  echo ""
  ok "=========================================="
  ok " PanelOut Bot is running"
  ok "=========================================="
  echo ""
  echo "  Webhook:   ${WEBHOOK_URL}${WEBHOOK_PATH}"
  echo "  FAQ page:  ${WEBHOOK_URL}/faq"
  echo "  App port:  ${PORT}"
  echo "  Postgres:  host port ${POSTGRES_PORT} (container internal: 5432)"
  echo "  Redis:     host port ${REDIS_PORT} (container internal: 6379)"
  echo "  Database:  ${DATABASE_URL}"
  echo "  Redis URL: ${REDIS_URL}"
  echo ""
  echo "  Live logs: ${COMPOSE_CMD[*]} logs -f app"
  echo "  Stop:      ${COMPOSE_CMD[*]} down"
  echo "  Adminer:   ${COMPOSE_CMD[*]} --profile tools up -d adminer"
  echo ""

  read -rp "Show application logs now? [Y/n]: " SHOW_LOGS
  SHOW_LOGS="${SHOW_LOGS:-y}"
  if [[ "$SHOW_LOGS" =~ ^[Yy]$ ]]; then
    "${COMPOSE_CMD[@]}" logs -f app
  fi
}

main "$@"
